export default {
  /* General */

  /* Page not found */
  'page-not-Found-label': 'Page not found!',
  'page-not-Found-return': 'Return',

  /* Character */
  'character.iam': 'I am',
  'character.iam-pilot': 'and I am a {starship} pilot',

  /* AppInfo */
  'app-info.application-running': 'Application running:',
  'app-info.on': 'on',
  'app-info.in': 'in',
  'app-info.dev-mode': 'Development mode',
  'app-info.stg-mode': 'Staging mode',
  'app-info.prod-mode': 'Production mode',

  /* Salutation */
  'salutation.text': 'This project was generated by R3-TS. Thank you for using it. Please send me your feedback.',

  /* Locate */
  'locate.language': 'Language'
};
